### ISSUE TITLE
How can I set default value

### ISSUE THREAD

**Issue by s4kibs4mi** [favadi/protoc-go-inject-field#1]
Example :
```
// @inject_field: tableName string = "hellos"
message Hello {
    string name = 1;
}
```

Output should be,
```
// custom fields getter/setter
func (m *Hello) TableName() string {
	return "hellos"
}
// No setter for field having default value
```

**Comment by favadi** [comment]
I'm not sure why getter of TableName field should always returns the fixed string "hellos" like in your example. Can you tell me your use case?

**Comment by favadi** [comment]
Close as lack of response, feel free to reopen.

**Comment by s4kibs4mi** [comment]
@favadi Actually my intention is to set default value for a specific field.
